version: "3.2"
services:
  hbase-docker:
    image: dajobe/hbase
    ports:
      - "9090:9090"
      - "9095:9095"
      - "8080:8080"
      - "2181:2181"
      - "16000:16000"
      - "16010:16010"
      - "16020:16020"
      - "16030:16030"
    hostname: hbase-docker
    container_name: hbase-docker
    volumes:
      - "./database/tables.txt:/tables.txt"
      - "./database/data:/data"
  api:
    build: app/
    ports:
      - "8000:8000"
    links:
      - hbase-docker
    depends_on:
      - hbase-docker

  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    links:
      - api

networks:
    default:
