version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "api/requirements.txt" }}
            - v1-dependencies-
      - run:
          command: |  
            sudo pip install virtualenv

      - run:
          name: install dependencies
          command: |
            cd api && make setup-venv

      - save_cache:
          paths:
            - ./api/venv
          key: v1-dependencies-{{ checksum "api/requirements.txt" }}

      - run:
          name: run tests
          command: |
            cd api && make test
